// 文件类型徽标：按扩展名映射颜色与缩写
import React from 'react'
import { extOf } from '../core/format.js'

const el = React.createElement

const FILE_STYLE = {
  js: { label: 'JS', bg: '#f0db4f', fg: '#1f2329' },
  mjs: { label: 'JS', bg: '#f0db4f', fg: '#1f2329' },
  cjs: { label: 'JS', bg: '#f0db4f', fg: '#1f2329' },
  ts: { label: 'TS', bg: '#3178c6', fg: '#ffffff' },
  tsx: { label: 'TSX', bg: '#3178c6', fg: '#ffffff' },
  jsx: { label: 'JSX', bg: '#61dafb', fg: '#1f2329' },
  json: { label: '{}', bg: '#c9a227', fg: '#ffffff' },
  jsonl: { label: '{}', bg: '#c9a227', fg: '#ffffff' },
  ndjson: { label: '{}', bg: '#c9a227', fg: '#ffffff' },
  html: { label: 'HTML', bg: '#e34c26', fg: '#ffffff' },
  htm: { label: 'HTML', bg: '#e34c26', fg: '#ffffff' },
  css: { label: 'CSS', bg: '#264de4', fg: '#ffffff' },
  scss: { label: 'SCSS', bg: '#cd6799', fg: '#ffffff' },
  less: { label: 'LESS', bg: '#1d365d', fg: '#ffffff' },
  md: { label: 'MD', bg: '#0aa0b5', fg: '#ffffff' },
  markdown: { label: 'MD', bg: '#0aa0b5', fg: '#ffffff' },
  txt: { label: 'TXT', bg: '#519aba', fg: '#ffffff' },
  log: { label: 'LOG', bg: '#5f6b7a', fg: '#ffffff' },
  py: { label: 'PY', bg: '#3776ab', fg: '#ffffff' },
  java: { label: 'JAVA', bg: '#e76f00', fg: '#ffffff' },
  c: { label: 'C', bg: '#5c6370', fg: '#ffffff' },
  h: { label: 'H', bg: '#a074c4', fg: '#ffffff' },
  cpp: { label: 'CPP', bg: '#00599c', fg: '#ffffff' },
  cc: { label: 'CPP', bg: '#00599c', fg: '#ffffff' },
  cxx: { label: 'CPP', bg: '#00599c', fg: '#ffffff' },
  hpp: { label: 'HPP', bg: '#00599c', fg: '#ffffff' },
  cs: { label: 'C#', bg: '#68217a', fg: '#ffffff' },
  go: { label: 'GO', bg: '#00add8', fg: '#ffffff' },
  rs: { label: 'RS', bg: '#dea584', fg: '#1f2329' },
  rb: { label: 'RB', bg: '#cc342d', fg: '#ffffff' },
  php: { label: 'PHP', bg: '#777bb3', fg: '#ffffff' },
  sh: { label: 'SH', bg: '#4eaa25', fg: '#ffffff' },
  bash: { label: 'SH', bg: '#4eaa25', fg: '#ffffff' },
  zsh: { label: 'SH', bg: '#4eaa25', fg: '#ffffff' },
  bat: { label: 'BAT', bg: '#c1f12e', fg: '#1f2329' },
  cmd: { label: 'CMD', bg: '#5c5c5c', fg: '#ffffff' },
  ps1: { label: 'PS1', bg: '#012456', fg: '#ffffff' },
  yml: { label: 'YML', bg: '#2e7d32', fg: '#ffffff' },
  yaml: { label: 'YAML', bg: '#2e7d32', fg: '#ffffff' },
  toml: { label: 'TOML', bg: '#9c4221', fg: '#ffffff' },
  ini: { label: 'INI', bg: '#607d8b', fg: '#ffffff' },
  cfg: { label: 'CFG', bg: '#607d8b', fg: '#ffffff' },
  conf: { label: 'CFG', bg: '#607d8b', fg: '#ffffff' },
  env: { label: 'ENV', bg: '#607d8b', fg: '#ffffff' },
  properties: { label: 'CFG', bg: '#607d8b', fg: '#ffffff' },
  xml: { label: 'XML', bg: '#0060ac', fg: '#ffffff' },
  sql: { label: 'SQL', bg: '#e38c00', fg: '#ffffff' },
  graphql: { label: 'GQL', bg: '#e10098', fg: '#ffffff' },
  vue: { label: 'VUE', bg: '#42b883', fg: '#ffffff' },
  svelte: { label: 'SVL', bg: '#ff3e00', fg: '#ffffff' },
  swift: { label: 'SWIFT', bg: '#f05138', fg: '#ffffff' },
  kt: { label: 'KT', bg: '#7f52ff', fg: '#ffffff' },
  kts: { label: 'KTS', bg: '#7f52ff', fg: '#ffffff' },
  kotlin: { label: 'KT', bg: '#7f52ff', fg: '#ffffff' },
  dart: { label: 'DART', bg: '#0175c2', fg: '#ffffff' },
  lua: { label: 'LUA', bg: '#000080', fg: '#ffffff' },
  r: { label: 'R', bg: '#276dc3', fg: '#ffffff' },
  scala: { label: 'SCALA', bg: '#dc322f', fg: '#ffffff' },
  clj: { label: 'CLJ', bg: '#5881d8', fg: '#ffffff' },
  hs: { label: 'HS', bg: '#5e5086', fg: '#ffffff' },
  ex: { label: 'EX', bg: '#7b53a0', fg: '#ffffff' },
  exs: { label: 'EXS', bg: '#7b53a0', fg: '#ffffff' },
  erl: { label: 'ERL', bg: '#b83998', fg: '#ffffff' },
  pl: { label: 'PL', bg: '#0298c3', fg: '#ffffff' },
  pm: { label: 'PM', bg: '#0298c3', fg: '#ffffff' },
  groovy: { label: 'GROVY', bg: '#4298b8', fg: '#ffffff' },
  gradle: { label: 'GRDLE', bg: '#02303a', fg: '#ffffff' },
  cmake: { label: 'CMAKE', bg: '#064f8c', fg: '#ffffff' },
  ninja: { label: 'NINJA', bg: '#7d88a4', fg: '#ffffff' },
  proto: { label: 'PROTO', bg: '#a5a5a5', fg: '#1f2329' },
  zig: { label: 'ZIG', bg: '#f7a41d', fg: '#1f2329' },
  nim: { label: 'NIM', bg: '#ffc200', fg: '#1f2329' },
  tex: { label: 'TEX', bg: '#3d6117', fg: '#ffffff' },
  rst: { label: 'RST', bg: '#4a4a4a', fg: '#ffffff' },
  adoc: { label: 'ADOC', bg: '#e40046', fg: '#ffffff' },
  org: { label: 'ORG', bg: '#77aa99', fg: '#1f2329' },
  csv: { label: 'CSV', bg: '#217346', fg: '#ffffff' },
  tsv: { label: 'TSV', bg: '#217346', fg: '#ffffff' },
  diff: { label: 'DIFF', bg: '#6f42c1', fg: '#ffffff' },
  patch: { label: 'PATCH', bg: '#6f42c1', fg: '#ffffff' },
  lock: { label: 'LOCK', bg: '#7a8290', fg: '#ffffff' },
  gitignore: { label: 'GIT', bg: '#e44c29', fg: '#ffffff' },
  wasm: { label: 'WASM', bg: '#654ff0', fg: '#ffffff' },
  png: { label: 'PNG', bg: '#9b59b6', fg: '#ffffff' },
  jpg: { label: 'JPG', bg: '#9b59b6', fg: '#ffffff' },
  jpeg: { label: 'JPG', bg: '#9b59b6', fg: '#ffffff' },
  gif: { label: 'GIF', bg: '#9b59b6', fg: '#ffffff' },
  webp: { label: 'WEBP', bg: '#9b59b6', fg: '#ffffff' },
  bmp: { label: 'BMP', bg: '#9b59b6', fg: '#ffffff' },
  svg: { label: 'SVG', bg: '#ffb13b', fg: '#1f2329' },
  ico: { label: 'ICO', bg: '#9b59b6', fg: '#ffffff' },
  avif: { label: 'AVIF', bg: '#9b59b6', fg: '#ffffff' },
}

export function fileBadge(name) {
  const ext = extOf(name)
  const st = FILE_STYLE[ext]
  if (st) return el('span', { className: 'fm-ficon', style: { backgroundColor: st.bg, color: st.fg } }, st.label)
  const label = ext ? ext.slice(0, 4).toUpperCase() : 'FILE'
  return el('span', { className: 'fm-ficon fm-ficon-other' }, label)
}
